export const TOKENS = {
  // Config
  Config: Symbol.for('Config'),

  // Infrastructures
  ClaudeCodeInfra: Symbol.for('ClaudeCodeInfra'),
  CommandRunnerInfra: Symbol.for('CommandRunnerInfra'),
  FileMoveInfra: Symbol.for('FileMoveInfra'),
  FsInfra: Symbol.for('FsInfra'),
  GitInfra: Symbol.for('GitInfra'),
  KnowledgeReaderInfra: Symbol.for('KnowledgeReaderInfra'),
  ProjectRootInfra: Symbol.for('ProjectRootInfra'),
  ShellInfra: Symbol.for('ShellInfra'),
  TestFileDiscoveryInfra: Symbol.for('TestFileDiscoveryInfra'),
  TsAnalyzer: Symbol.for('TsAnalyzer'),
  TsAnalyzerSkipAddFiles: Symbol.for('TsAnalyzerSkipAddFiles'),
  TtyInfra: Symbol.for('TtyInfra'),

  // Repositories
  CheckerRepository: Symbol.for('CheckerRepository'),
  PlanFileRepository: Symbol.for('PlanFileRepository'),
  ClaudeCodeRepository: Symbol.for('ClaudeCodeRepository'),
  ClaudeSessionRepository: Symbol.for('ClaudeSessionRepository'),
  GitRepository: Symbol.for('GitRepository'),
  KnowledgeSearchRepository: Symbol.for('KnowledgeSearchRepository'),
  PermissionPipeRepository: Symbol.for('PermissionPipeRepository'),
  PipelineFileRepository: Symbol.for('PipelineFileRepository'),
  ProcedureRepository: Symbol.for('ProcedureRepository'),
  RejectionFeedbackRepository: Symbol.for('RejectionFeedbackRepository'),
  SessionRepository: Symbol.for('SessionRepository'),
  ShellRepository: Symbol.for('ShellRepository'),
  TestStrategyRepository: Symbol.for('TestStrategyRepository'),
  TsAnalysisRepository: Symbol.for('TsAnalysisRepository'),

  // Domains
  AgentDomain: Symbol.for('AgentDomain'),
  PlanFileDomain: Symbol.for('PlanFileDomain'),
  AnalyzeDomain: Symbol.for('AnalyzeDomain'),
  CheckerDomain: Symbol.for('CheckerDomain'),
  GitPendingChangesDomain: Symbol.for('GitPendingChangesDomain'),
  ImportDomain: Symbol.for('ImportDomain'),
  KnowledgeSearchDomain: Symbol.for('KnowledgeSearchDomain'),
  PermissionPipeDomain: Symbol.for('PermissionPipeDomain'),
  PipelineDomain: Symbol.for('PipelineDomain'),
  PipelineFileDomain: Symbol.for('PipelineFileDomain'),
  PipelineLoaderDomain: Symbol.for('PipelineLoaderDomain'),
  PipelineTaskDomain: Symbol.for('PipelineTaskDomain'),
  ScriptDomain: Symbol.for('ScriptDomain'),
  SessionDomain: Symbol.for('SessionDomain'),
  TestStrategyDomain: Symbol.for('TestStrategyDomain'),
  TsAnalysisDomain: Symbol.for('TsAnalysisDomain'),

  // Services
  AbortService: Symbol.for('AbortService'),
  PlanFileService: Symbol.for('PlanFileService'),
  AgentService: Symbol.for('AgentService'),
  AnalyzeService: Symbol.for('AnalyzeService'),
  CheckerService: Symbol.for('CheckerService'),
  GitPendingChangesService: Symbol.for('GitPendingChangesService'),
  ImportService: Symbol.for('ImportService'),
  KnowledgeSearchService: Symbol.for('KnowledgeSearchService'),
  PermissionPipeService: Symbol.for('PermissionPipeService'),
  PipelineFileService: Symbol.for('PipelineFileService'),
  PipelineService: Symbol.for('PipelineService'),
  SessionService: Symbol.for('SessionService'),
  TestStrategistService: Symbol.for('TestStrategistService'),
  TsAnalysisService: Symbol.for('TsAnalysisService')
} as const
