export const TOKENS = {
  // Config
  Config: Symbol.for('Config'),
  // Domains
  SessionDomain: Symbol.for('SessionDomain'),
  AgentDomain: Symbol.for('AgentDomain'),
  PipelineDomain: Symbol.for('PipelineDomain'),
  PipelineFileDomain: Symbol.for('PipelineFileDomain'),
  AnalyzeDomain: Symbol.for('AnalyzeDomain'),
  ImportDomain: Symbol.for('ImportDomain'),
  CheckerDomain: Symbol.for('CheckerDomain'),
  TestStrategyDomain: Symbol.for('TestStrategyDomain'),
  ScriptDomain: Symbol.for('ScriptDomain'),
  // Services
  SessionService: Symbol.for('SessionService'),
  AgentService: Symbol.for('AgentService'),
  PipelineService: Symbol.for('PipelineService'),
  PipelineFileService: Symbol.for('PipelineFileService'),
  AnalyzeService: Symbol.for('AnalyzeService'),
  ImportService: Symbol.for('ImportService'),
  CheckerService: Symbol.for('CheckerService'),
  TestStrategistService: Symbol.for('TestStrategistService'),
  TsAnalysisService: Symbol.for('TsAnalysisService'),
  // Repositories
  PermissionPipeRepository: Symbol.for('PermissionPipeRepository'),
  FileMoveRepository: Symbol.for('FileMoveRepository'),
  GitRepository: Symbol.for('GitRepository'),
  RejectionFeedbackRepository: Symbol.for('RejectionFeedbackRepository'),
  ClaudeCodeRepository: Symbol.for('ClaudeCodeRepository'),
  SessionRepository: Symbol.for('SessionRepository'),
  ClaudeSessionRepository: Symbol.for('ClaudeSessionRepository'),
  ProcedureRepository: Symbol.for('ProcedureRepository'),
  CheckerRepository: Symbol.for('CheckerRepository'),
  TestStrategyRepository: Symbol.for('TestStrategyRepository'),
  ShellRepository: Symbol.for('ShellRepository'),
  KnowledgeSearchRepository: Symbol.for('KnowledgeSearchRepository'),
  TsAnalysisRepository: Symbol.for('TsAnalysisRepository'),
  // Domains
  KnowledgeSearchDomain: Symbol.for('KnowledgeSearchDomain'),
  TsAnalysisDomain: Symbol.for('TsAnalysisDomain'),
  PermissionPipeDomain: Symbol.for('PermissionPipeDomain'),
  // Services
  KnowledgeSearchService: Symbol.for('KnowledgeSearchService'),
  PermissionPipeService: Symbol.for('PermissionPipeService')
} as const
